
// create action type

// get brand
export const GET_BRANDS_REQUEST = "GET_BRANDS_REQUEST"
export const GET_BRANDS_SUCCESS = "GET_BRANDS_SUCCESS"
export const GET_BRANDS_FAILED = "GET_BRANDS_FAILED"

// create brand
export const CREATE_BRANDS_REQUEST = "CREATE_BRANDS_REQUEST"
export const CREATE_BRANDS_SUCCESS = "CREATE_BRANDS_SUCCESS"
export const CREATE_BRANDS_FAILED = "CREATE_BRANDS_FAILED"

// delete brand
export const DELETE_BRAND_REQUEST = "DELETE_BRAND_REQUEST"
export const DELETE_BRAND_SUCCESS = "DELETE_BRAND_SUCCESS"
export const DELETE_BRAND_FAILED = "DELETE_BRAND_FAILED"

export const UPDATE_STATUS_SUCCESS = "UPDATE_BRAND_SUCCESS" 
export const UPDATE_STATUS_FAILED = "UPDATE_BRAND_FAILED" 

export const UPDATE_BRAND_SUCCESS = "UPDATE_BRAND_SUCCESS"
export const UPDATE_BRAND_FAILED = "UPDATE_BRAND_FAILED"